### ISSUE TITLE
Default Language is always selected in Android 10

### ISSUE THREAD

**Issue by MobilyteApps** [CrossGeeks/MultilingualXFSample#2]
Hi,

Previously my Visual studio version was 16.3.2 with the help of plugin.multilingual i was able to convert language but when i updated my visual studio to 16.6, the default language is always selected.

My default language  is Spanish and always sheen Spanish i want to convert different labnguage,

I have uninstall the plugin.multilingual and  removed the Transalation.cs  page and follow according to given steps.

I am not getting that. I am attaching the resource file 👎 

[Resources.zip](https://github.com/CrossGeeks/MultilingualXFSample/files/4691850/Resources.zip)

**Comment by Char0394** [comment]
If you are using VS for mac try the latest stable version(8.6.1(build 26).

**Comment by MobilyteApps** [comment]
I am not using VS for MAC, My Problem is in VS for Window 16.6 version.

**Comment by Char0394** [comment]
The issue is with visual studio not with the code. Check this ticket: https://github.com/xamarin/xamarin-android/issues/4664#issuecomment-632986668

**Comment by MobilyteApps** [comment]
@Char0394 :- This is not the issue of the code and plugin, this issue is for visual studio windows version 16.6, i downgrade version from 16.6 to 16.3.2 and my code works. This is so much frustrating.

Thanks for support,

**Comment by Zubairhanif06** [comment]
@MobilyteApps  could you please guide me ,how i can downgrade version from 16.6 to 16.3.2 and my code works.
thank you

**Comment by MobilyteApps** [comment]
@Zubairhanif06 :- You can download from visual studio https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

**Comment by Zubairhanif06** [comment]
@MobilyteApps  i'm using community edition . i already read this but i did not understand what to do.
this is really so much frustrating.

**Comment by MobilyteApps** [comment]
@Zubairhanif06:- Can you please uninstall the community version and install the professional version  https://docs.microsoft.com/en-us/visualstudio/releases/2019/history because you do not have option to degrade in community version.

Thanks

**Comment by Zubairhanif06** [comment]
okay ,Thank you
